### ISSUE TITLE
seq2seq

### ISSUE THREAD

**Issue by kutoga** [philipperemy/keras-seq2seq-example#1]
I'm sorry, but it seems you did not implement the seq2seq model? Or at least I cannot see how you pass the internal state of the encoder to the decoder?

I would be highly interested if you could do this:)!

**Comment by philipperemy** [comment]
@kutoga hey thanks for your question!

I took most of the code from this Keras example:

https://github.com/fchollet/keras/blob/master/examples/addition_rnn.py

As mentioned in their implementation, the paper of interest was named "Sequence to Sequence Learning with Neural Networks".

Link is http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf

It's a seq2seq model because both the input and output are sequences.

But I guess you have several ways to implement seq2seq models. 

Somehow my code is a simplified version of this one:

```
m.add(RNN(HIDDEN_SIZE, input_shape=(INPUT_MAX_LEN, len(chars))))
m.add(Dense(OUTPUT_MAX_LEN * len(chars)))
m.add(Reshape((OUTPUT_MAX_LEN, len(chars))))
m.add(TimeDistributed(Dense(len(chars), activation='softmax')))
```

In this code, only the last states are propagated to the next layers. So roughly 

```
m.add(RNN(HIDDEN_SIZE, input_shape=(INPUT_MAX_LEN, len(chars))))
```

would be the encoder and:

```
m.add(Dense(OUTPUT_MAX_LEN * len(chars)))
m.add(Reshape((OUTPUT_MAX_LEN, len(chars))))
m.add(TimeDistributed(Dense(len(chars), activation='softmax')))
```

the decoder. (The states are the output of the RNN layer).

Again, it's a very simplified version of a real seq2seq model, used in machine translation (english -> french).

**Comment by kutoga** [comment]
Thansk for the answer:)!

Ok, I see. I just was confused, because of the image in the repository:
![687474703a2f2f73757269796164656570616e2e6769746875622e696f2f696d672f736571327365712f73657132736571322e706e67](https://user-images.githubusercontent.com/19676199/33827826-0223eba8-de6a-11e7-8a10-d2161d18c56a.png)

On this image it can be seen that the internal state of the LSTM cell is passed from the encoder to the decoder (and the decoder uses its own output values as inputs), but in the code the output of one LSTM-layer is used as input for another LSTM layer.

Probably this also works for many problem statements and I do not even know if it makes really a difference. Probably, both models work very similar:)

Anyway, thanks for sharing your code:)! And thanks for answering my question:)!
